version: "3"

services:
  users-db:
    container_name: users-db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: postgres
      POSTGRES_DB: user_login
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
